{% set name = "dggrid" %}
{% set version = "7.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/allixender/DGGRID/archive/refs/tags/v{{ version }}-conda1.tar.gz
  sha256: cf1e43af5b116b4dd990f19b1681f38d0694afdf43fcef1d73a99be12bdd53de

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake >=3.12,<4
    - make  # [linux]
  host:
    - libgdal
    - shapelib
  run:
    - libgdal
    - shapelib

test:
  commands:
    - test -f ${PREFIX}/bin/dggrid
    - if not exist %LIBRARY_BIN%\dggrid exit 1  # [win]

about:
  home: https://github.com/sahrk/DGGRID
  license: AGPL-3.0-or-later
  license_file: LICENSE
  summary: A command-line application that generates and manipulates icosahedral discrete global grids.

  dev_url: https://github.com/sahrk/DGGRID

extra:
  recipe-maintainers:
    - allixender
