{% set name = "dggrid" %}
{% set version = "8.1b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/allixender/DGGRID/archive/refs/tags/v{{ version }}-conda1.tar.gz
  sha256: e6b11bf13a7584514dde92e4499a31aa2c68d3e23784a75c77d7a97ec982988c

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake >=3.19,<4
    - make  # [not win]
    - ninja  # [win]
  host:
    - libgdal
    - shapelib
  run:
    - libgdal
    - shapelib

test:
  commands:
    - dggrid -v
    - dggrid.exe -v  # [win]

about:
  home: https://github.com/sahrk/DGGRID
  license: AGPL-3.0-or-later
  license_file: LICENSE
  summary: A command-line application that generates and manipulates icosahedral discrete global grids.

  dev_url: https://github.com/sahrk/DGGRID

extra:
  recipe-maintainers:
    - allixender
