{% set name = "dggrid" %}
{% set version = "8.43" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/sahrk/DGGRID/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3ed807e14e94e217bee97a88df78b7b96a96d53f5bbeca46b8f6715c6b4f4b59

build:
  number: 1

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake >=3.19,<4
    - make  # [not win]
    - ninja  # [win]
  host:
    - libgdal
    - shapelib
  run:
    - libgdal
    - shapelib

test:
  commands:
    - dggrid -v
    - dggrid.exe -v  # [win]

about:
  home: https://github.com/sahrk/DGGRID
  license: AGPL-3.0-or-later
  license_file: LICENSE
  summary: A command-line application that generates and manipulates icosahedral discrete global grids.

  dev_url: https://github.com/sahrk/DGGRID

extra:
  recipe-maintainers:
    - allixender
