{% set name = "dggrid" %}
{% set version = "8.44" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/sahrk/DGGRID/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ce3e0708121d8b6ae48683517de7cdece7547f0dc5bb48ce0e31a618767e5d56

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake >=3.19,<4
    - make  # [not win]
    - ninja  # [win]
  host:
    - libgdal
    - shapelib
  run:
    - libgdal
    - shapelib

test:
  commands:
    - dggrid -v
    - dggrid.exe -v  # [win]

about:
  home: https://github.com/sahrk/DGGRID
  license: AGPL-3.0-or-later
  license_file: LICENSE
  summary: A command-line application that generates and manipulates icosahedral discrete global grids.

  dev_url: https://github.com/sahrk/DGGRID

extra:
  recipe-maintainers:
    - allixender
